### ISSUE TITLE
Remove vendor directory from git

### ISSUE THREAD

**Issue by GawainLynch** [toog/customfields#1]
Shipping a vendor directory in an extension will only lead to :crying_cat_face: 

Can I suggest that you remove the vendor folder from git, then add a `.gitignore` file to the project root, with a *minimum* contents of:

```
vendor/
```

**Comment by pchabbert** [comment]
Yes you're rigth,  Of course, i'll do it next week.

I didnt write it in README.md but this project is under construction and
many things will change.

Thanks you for your comment.

Have a good day.

CHABBERT Philippe

**Comment by GawainLynch** [comment]
Totally zero stress here… we just saw it and worried that it slipped though somebody's attention. :+1:

**Comment by pchabbert** [comment]
That's ok. I'm not stress. ;) 

Vendor was removed and gitignore added.
