### ISSUE TITLE
Issue with Bolt 3.1

### ISSUE THREAD

**Issue by eduardomart** [toog/customfields#2]
v.1.0.0 not compatible with Bolt 3.1. 
It triggers this error:
`Strict Standards: Declaration of Bolt\Extension\Toog\CustomFields\CustomFieldsExtension::registerServices() should be compatible with Bolt\Extension\SimpleExtension::registerServices(Silex\Application $app) in /home/extensions/vendor/toog/customfields/src/CustomFieldsExtension.php on line 42`

**Comment by nnussbaum** [comment]
Thank you
